name       : gnome-shell-extension-dynamic-panel-transparency
version    : '24'
release    : 5
source     :
    - https://github.com/rockon999/dynamic-panel-transparency/archive/v24.tar.gz : eb7fa9e7514fa078f06a39251895f13905db16d9682e824bb4870767f3b6e78d
license    : GPL-2.0
component  : desktop.gnome
summary    : This extension adds transparency to the Gnome Shell panel.
description: |
    This extension adds transparency to the Gnome Shell panel.
rundeps    :
    - gnome-shell
    - gnome-shell-extensions
install    : |
    export gseDir=$installdir/usr/share/gnome-shell/extensions/
    install -dm00755 $installdir/usr/share/glib-2.0/schemas/
    install -dm00755 ${gseDir}
    install -Dm00644 dyn*/schemas/org.* $installdir/usr/share/glib-2.0/schemas/
    rm -r dyn*/schemas
    cp -R $workdir/dynamic-panel* ${gseDir}
    chmod 00644 ${gseDir}
