name       : gnome-shell-extension-dynamic-panel-transparency
version    : '21'
release    : 4
source     :
    - https://github.com/rockon999/dynamic-panel-transparency/archive/v21.tar.gz : 9608324253ff6e210166f0a44c3ee73ff546c53f52bc93143afa2e09fe3231e0
license    : GPL-2.0
component  : desktop.gnome
summary    : This extension adds transparency to the Gnome Shell panel.
description: |
    This extension adds transparency to the Gnome Shell panel.
rundeps    :
    - gnome-shell
    - gnome-shell-extensions
install    : |
    export gseDir=$installdir/usr/share/gnome-shell/extensions/
    install -dm00755 $installdir/usr/share/glib-2.0/schemas/
    install -dm00755 ${gseDir}
    install -Dm00644 dyn*/schemas/org.* $installdir/usr/share/glib-2.0/schemas/
    rm -r dyn*/schemas
    cp -R $workdir/dynamic-panel* ${gseDir}
    chmod 00644 ${gseDir}
