name       : gnome-shell-extension-dynamic-panel-transparency
version    : '25'
release    : 6
source     :
    - https://github.com/rockon999/dynamic-panel-transparency/archive/v25.tar.gz : 667317443dc0c5924ef9327d885983f87f826dbc9b7e21f2dd973f91b4edac8f
license    : GPL-2.0
component  : desktop.gnome
summary    : This extension adds transparency to the Gnome Shell panel.
description: |
    This extension adds transparency to the Gnome Shell panel.
rundeps    :
    - gnome-shell
    - gnome-shell-extensions
install    : |
    export gseDir=$installdir/usr/share/gnome-shell/extensions/
    install -dm00755 $installdir/usr/share/glib-2.0/schemas/
    install -dm00755 ${gseDir}
    install -Dm00644 dyn*/schemas/org.* $installdir/usr/share/glib-2.0/schemas/
    rm -r dyn*/schemas
    cp -R $workdir/dynamic-panel* ${gseDir}
    chmod 00644 ${gseDir}
